# render.yaml - DÃ©ploiement Laravel avec storage, Breeze et MySQL
services:
  - type: web
    name: SIR-Gestion DMA-app
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
      php artisan storage:link
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://{{ .Gestion des DMA }}.onrender.com
      - key: APP_KEY
        generateValue: true
      # Database
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: laravel-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: laravel-db
          property: port
      - key: DB_DATABASE
        value: bd_demande1
      - key: DB_USERNAME
        fromDatabase:
          name: laravel-db
          property: user
      - key: DB_PASSWORD
        value: 2006
      # Mail (exemple Mailtrap)
  #    - key: MAIL_MAILER
    #    value: smtp
   #   - key: MAIL_HOST
   #     value: sandbox.smtp.mailtrap.io
   #   - key: MAIL_PORT
   #     value: 2525
   #   - key: MAIL_USERNAME
   #     value: your_mailtrap_user
   #   - key: MAIL_PASSWORD
   #     value: your_mailtrap_password
    #  - key: MAIL_ENCRYPTION
    #    value: tls
    #  - key: MAIL_FROM_ADDRESS
     #   value: noreply@tonapp.com
     # - key: MAIL_FROM_NAME
    #    value: MonApp

databases:
  - name: laravel-db
    plan: free
    databaseName: bd_demande1
    user: root
    password: 2006
